future/urls.py
from django.conf.urls.defaults import patterns, include, url
from futureapp.views import * 
from django.conf import settings

from os import environ

# Dynamically match hashtags to urls that do not match any other rules
# and pass them to the hash filtered function
# this function influenced by:
# https://github.com/semente/django-hashtags
hashtagged_url = url(
    regex  = '^(?P<hashtag>[-\w]+)/$',
    view = renderHashfiltered,
    name = 'hashtagged_url'
    )

# Main URL patterns, see futureapp.views for more details
urlpatterns = patterns('',
                       url(r'^$',groc_drop),
                       #url(r'^$',drop),
                       url(r'^post/$',post),
                       url(r'^deletePost/$',deletePost),
                       #url(r'^home/$',renderHomepage),
                       url(r'^addItem/$', addNewItem),
                       url(r'^suggestionAdd/$', addFromSuggestions),
                       url(r'^shoppingRemove/$', removeFromShopping),
                       url(r'^suggestionRemove/$', removeFromSuggestions),
                       url(r'^home/$',renderGrocHomepage),
                       url(r'^initLists/$',initializeLists),
                       url(r'^archive/$',archiveShoppingList),
                       url(r'^fbauth/$',fbauth),
                       url(r'^signup/$',signup),
                       url(r'^newuser/$',newuser),
                       url(r'^createuser/$',createuser),
                       url(r'^directory/$',directory),
                       url(r'^menu/$',renderMenu),
                       url(r'^postMenu/$',postMenu),
                       url(r'^announcements/$',renderAnnouncements),
                       url(r'^deleteMenu/$',deleteMenu),
                       url(r'^logout/$',logout),
                       url(r'^postComment/$',postComment),
                       url(r'^deleteComment/$',deleteComment),
                       url(r'^user/(\w+-\w+)/$', renderProfile),
                       url(r'^search/$', renderHomepage),
                       url(r'^search/$', search),
                       url(r'^lobby/$',renderLobby),
                       url(r'^gameForm/$',renderGameForm),
                       url(r'^createGame/$',createGame),
                       url(r'^gameDisplayDummy/$',renderGameList),
                       url(r'^joinGame/$',joinGame),
                       url(r'^leaveGame/$',leaveGame),
                       url(r'^deleteGame/$',deleteGame),
                       url(r'^inactivateGame/$',inactivateGame),
                       url(r'^renderFilteredLobby/$', renderFilteredLobby),
                       hashtagged_url,
                       )

# URL patterns for static files (images, css, javascript)

if environ.has_key('FUTURE_DIR'):
    # local
  urlpatterns += patterns('',
                         (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
                         )
else:
  urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
  )

future/futureapp/models.py
from django.db import models
from django.forms import ModelForm

### Groceries stuff begins here ###

class Item(models.Model):
    name = models.CharField("name", max_length = 100)   # The name of the item.
    frequency = models.IntegerField("frequency")        # Number of times bought.

class List(models.Model):
    # For now there is only one list. Later, I might save all the lists.
    items = models.ManyToManyField(Item)

class ShoppingList(List):
    # Current list of items to be bought.
    pass

class SuggestionList(List):
    # A list of suggested items.
    pass

### Groceries stuff ends here ###


# A user of the Web F. Site
class User(models.Model):
    CLASS_YEAR_CHOICES = ( 
        (u'2012', u'Senior'),
        (u'2013', u'Junior'),
        (u'2014', u'Sophomore')
    )
    ADMIN_TITLE_CHOICES = (
        (u'ME', u'Member'),
        (u'OF', u'Officer'),
        (u'FC', u'Food Chair'),
        (u'BAMF', u'Developer')
    )

    # Basic user information
    netid = models.CharField(max_length=8, unique=True)
    firstname = models.CharField("first name", max_length=30)
    lastname = models.CharField("last name", max_length=30)
    year = models.IntegerField("class year", max_length=4, choices=CLASS_YEAR_CHOICES)
    
    # User's facebook id, a unique integer, also used as our
    # authentication hook when a user visits the site
    fbid = models.BigIntegerField("facebook ID",unique=True,null=True)
    
    # Information for authenticating new users. Code must be provided
    # to match netids with facebook accounts, verifying identity.
    authenticated = models.BooleanField("user authenticated?")
    authcode = models.CharField("authentication code", max_length=40)
    
    # Permissions of the user for administrative purposes
    admin = models.CharField("administrator title", max_length=4, choices=ADMIN_TITLE_CHOICES)
    
    # URLS for different sizes of pictures, pulled from facebook's cdn
    # for now
    pic = models.CharField("facebook profile picture URL", max_length=70,blank=True)
    largepic = models.CharField("large facebook profile picture URL", max_length=70,blank=True)
    
    #  Internal database representation of facebook friend relationship
    friends = models.ManyToManyField("self")
    isfriend = False # rendered at page display time for access in
    # template language using the friends many to many relationship    

# A tag is a hashtag, consisting of a short amount of text and linked
# to posts by a many to many relationship where each post can have
# many tags and each tag can tag many posts
class Tag(models.Model):
    text = models.CharField("tag text", max_length=24)
    time = models.DateTimeField(auto_now_add=True)

# Post here is a superclass for many kinds of things that are posted,
# containing fields that are used in multiple types
class Post(models.Model):
    
    author = models.ForeignKey(User)
    text = models.TextField("post text")
    time = models.DateTimeField(auto_now_add=True)
    Tags = models.ManyToManyField(Tag)
    mentions = models.ManyToManyField(User, related_name="mentioned_posts") 
    hasvideo = models.BooleanField("Contains a youtube URL")
    youtubeid = models.CharField("Youtube Video Id", max_length=12, blank=True)
        
# A general purpose post, the main type of social content on the site
class UserPost(Post):
    announce = models.BooleanField("True if post is announcement.")
    
# A menu, no special information for now
class MenuPost(Post):
    pass

# A comment, subordinate to other posts
class Comment(Post):
    parent = models.ForeignKey(UserPost)    

# ---------------------------------------#

class Game(models.Model):
    """ Game model """
    SPORT_CHOICES = (
        (u'bskt', u'Basketball'),
        (u'tnns', u'Tennis'),
        (u'sccr', u'Soccer'),
    )

    GAME_STYLES = (
        (u'casu', u'casual'),
        (u'comp', u'competitive'),
    )

    STATUS_CHOICES = (
        (u'actv', u'active'),
        (u'inac', u'inactive'),
    )

    # User info:
    leader = models.ForeignKey(User) # only one leader per post.
    players = models.ManyToManyField(User, related_name='user_joined_games')
    #TODO: I don't know what related_name is.

    # metadata
    status = models.CharField('Game Status', max_length=4, choices=STATUS_CHOICES)
    creation_time = models.DateTimeField(auto_now_add=True)
    name = models.CharField('Game Name', max_length=30)
    sport = models.CharField('Game Type', max_length=4, choices=SPORT_CHOICES)
    location = models.CharField('Game Location', max_length=100)
    game_datetime = models.CharField('Game Datetime', max_length=50) #TODO: Change me
    style = models.CharField('Game Style', max_length=4, choices=GAME_STYLES)
    min_number_players = models.IntegerField('min number of players', max_length=2)
    max_number_players = models.IntegerField('max number of players', max_length=2)

future/templates/2-col-portfolio.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Two Column Portfolio Template for Bootstrap 3</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <!-- Custom CSS for the 'Thumbnail Gallery' Template -->
    <link href="/static/css/2-col-portfolio.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://startbootstrap.com">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#about">About</a></li>
            <li><a href="#services">Services</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
    
    <div class="container">

      <div class="row">
      
        <div class="col-lg-12">
          <h1 class="page-header">2 Col Portfolio <small>Showcase Your Work Two Columns at a Time</small></h1>
        </div>

      </div>

      <div class="row">
        
        <div class="col-lg-6 col-md-6 portfolio-item">
          <a href="#project-one"><img class="img-responsive" src="http://placehold.it/700x400"></a>
          <h3><a href="#project-one">Project One</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>

        <div class="col-lg-6 col-md-6 portfolio-item">
          <a href="#project-two"><img class="img-responsive" src="http://placehold.it/700x400"></a>
          <h3><a href="#project-two">Project Two</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>

      </div>

      <div class="row">
        
        <div class="col-lg-6 col-md-6 portfolio-item">
          <a href="#project-three"><img class="img-responsive" src="http://placehold.it/700x400"></a>
          <h3><a href="#project-three">Project Three</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>

        <div class="col-lg-6 col-md-6 portfolio-item">
          <a href="#project-four"><img class="img-responsive" src="http://placehold.it/700x400"></a>
          <h3><a href="#project-four">Project Four</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>

      </div>

      <div class="row">
        
        <div class="col-lg-6 col-md-6 portfolio-item">
          <a href="#project-five"><img class="img-responsive" src="http://placehold.it/700x400"></a>
          <h3><a href="#project-five">Project Five</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>

        <div class="col-lg-6 col-md-6 portfolio-item">
          <a href="#project-six"><img class="img-responsive" src="http://placehold.it/700x400"></a>
          <h3><a href="#project-six">Project Six</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>

      </div>


      <hr>

      <div class="row text-center">
        
        <div class="col-lg-12">
          <ul class="pagination">
            <li><a href="#">&laquo;</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&raquo;</a></li>
          </ul>        
        </div>

      </div>

      <hr>

      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; Company 2013</p>
          </div>
        </div>
      </footer>
      
    </div><!-- /.container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

  </body>

</html>

future/templates/add_game.html
	<!-- Adding a game form -->
	<div class="add-game-cont">
		<div id="add-game-screen">
			<div style="width: 100%; font-weight: 200; font-size: 30px; text-align:center; margin-bottom: 5px;">
				<img src="/static/images/close.png" class="close-button" style="height: 50px;
															position: relative;
															top: -45px;
															right: -45px;
															float: right;
															cursor: pointer;">
				<u>Create a New Game</u></div>
			<form name="input" action="/createGame/" method="post">
              {% csrf_token %}
              	<div style="float: left; padding-right: 50px;">
					Game Title:<br>
						<input type="text" name="name">
				</div>
				<div style="float: left; padding-right: 50px;">
				Location: <br>
					<input type="text" name="location">
				</div>
				<div style="float: left; padding-right: 50px;">
				Sport: <br>
					<select name="sport">
					  <option value="tnns">Tennis</option>
					  <option value="bskt">Basketball</option>
					  <option value="sccr">Soccer</option>
					</select>
				</div>
				<br><br><br><br>
				<div style="float: left; padding-right: 50px;">
				Challenge Level: <br>
					<input type="radio" name="style" value="casu">Casual<br>
					<input type="radio" name="style" value="comp">Competitive<br><br>
				</div>
				<br>
					<br><br><br><br>
				<div style="float: left;padding-right: 50px;">
				Date: <br>
					<input type="datetime-local" name="datetime"> <br>
				</div>
				<div style="float: left;">
				Players: <br>
					Min:  <input type="number" name="min_players"> <br>Max: <input type="number" name="max_players"><br>
					<br>
				</div>
				<br><br><br><br>
				Notes: <br>				
					<textarea name="notes" rows="4" cols="50"></textarea> <br>
					<br>
			 <div style="width: 100%; text-align:center;">
			 	<input type="submit" class="button" value="Submit"></div>
			</form>
		</div>
	 </div>

future/templates/bootstrap.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Two Column Portfolio Template for Bootstrap 3</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.css" rel="stylesheet">

    <!-- Custom CSS for the 'Thumbnail Gallery' Template -->
    <link href="/static/css/2-col-portfolio.css" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://startbootstrap.com">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><a href="#about">About</a></li>
            <li><a href="#services">Services</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>
    
    <div class="container">

      <div class="row">
      
        <div class="col-lg-12">
          <h1 class="page-header">2 Col Portfolio <small>Showcase Your Work Two Columns at a Time</small></h1>
        </div>

      </div>

      <div class="row">
        
        <div class="col-lg-6 col-md-6 portfolio-item">
          <a href="#project-one"><img class="img-responsive" src="http://placehold.it/700x400"></a>
          <h3><a href="#project-one">Project One</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>

          
        </div>

        <div class="col-lg-6 col-md-6 portfolio-item">
          <a href="#project-two"><img class="img-responsive" src="http://placehold.it/700x400"></a>
          <h3><a href="#project-two">Project Two</a></h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
        </div>

      </div>


      <hr>

      <div class="row text-center">
        
        <div class="col-lg-12">
          <ul class="pagination">
            <li><a href="#">&laquo;</a></li>
            <li class="active"><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li><a href="#">&raquo;</a></li>
          </ul>        
        </div>

      </div>

      <hr>

      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; Company 2013</p>
          </div>
        </div>
      </footer>
      
    </div><!-- /.container -->

    <!-- JavaScript -->
    <script src="js/jquery-1.10.2.js"></script>
    <script src="js/bootstrap.js"></script>

  </body>

</html>

future/templates/card.html
			<!-- Admin Games Info -->
			<div class="sidebar-game-list-title">My Admin Games</div>
			<div class="sidebar-break" style="height: 1px;"></div>
			<div class="sidebar-game-list">
			  {% for game in games_leading %}	
				<div class="card" style="padding-bottom: 1px;">
					<div class="cardTooltip">
						<div class="icon" style="background-repeat: no-repeat; 
												 height: 150px; width: 150px; 
												 background-size: cover; display: block;
												 background-image: url('/static/images/{{ game.sport }}larger.png');"></div>
						<div class="game-title">{{ game.name }}</div>
						<div class="game-sport">{{ game.get_sport_display }} </div><br>
						<div class="thisDate" id="{{game.game_datetime}}"></div>
						<div class="textual-info">
							A {% if game.style == "comp" %}
								    competitive
								{% else %}
								    casual
								{% endif %}
							game of {{ game.get_sport_display }}
							at {{ game.location }},  <div class="fillDate"></div><br>
							<em>{{ game.notes }}</em>
							{{game.min_number_players}} - {{game.max_number_players}} players<br>
							Players:<br>
							{% for player in game.players.all %}
								<a href=http://facebook.com/{{player.fbid}}> {{ player.firstname }} </a><br>
							{% endfor %}
							<div class="buttons">	
					        <form action="/leaveGame/" method="post" style="float: right;">
					          {% csrf_token %}
							  <button href="#" class="button">Leave Game</button>
					          <input type="hidden" name="game_to_leave_pk" value={{game.pk}} />
					        </form>
							</div>
						</div>
					</div>
					<div class="icon" 
						 style="background-image: url('/static/images/{{ game.sport }}.png');">
						<img src="/static/images/{{ game.style }}.png" alt="skill" class="skill">
					</div>
					<div class="card-text">
						<div class="card-date">{{ game.name }}</div>
						<br>
						<div class="card-location">{{ game.location }}</div>
						<br>
						<div class="card-capacity">{{ game.players.count }} / {{ game.max_number_players }}</div>
					</div>
				</div>
  			{% endfor %}
			</div>
			<div class="sidebar-break" style="height: 1px;"></div>
			<!-- Joined Games Info -->
			<div class="sidebar-game-list-title">Joined Games</div>
			<div class="sidebar-break" style="height: 1px;"></div>
			<div class="sidebar-game-list">
			  {% for game in games_playing %}	
				<div class="card" style="padding-bottom: 1px;">
					<div class="cardTooltip">
						<div class="icon" style="background-repeat: no-repeat; 
												 height: 150px; width: 150px; 
												 background-size: cover; display: block;
												 background-image: url('/static/images/{{ game.sport }}larger.png');"></div>
						<div class="game-title">{{ game.name }}</div>
						<div class="game-sport">{{ game.get_sport_display }} </div><br>
						<div class="thisDate" id="{{game.game_datetime}}"></div>
						<div class="textual-info">
							A {% if game.style == "comp" %}
								    competitive
								{% else %}
								    casual
								{% endif %}
							game of {{ game.get_sport_display }}
							at {{ game.location }},  <div class="fillDate"></div><br>
							<em>{{ game.notes }}</em><br>
							{{game.min_number_players}} - {{game.max_number_players}} players<br>
							Players:<br>
							{% for player in game.players.all %}
								<a href=http://facebook.com/{{player.fbid}}> {{ player.firstname }} </a><br>
							{% endfor %}
							<div class="buttons">	
					        <form action="/leaveGame/" method="post" style="float: right;">
					          {% csrf_token %}
							  <button href="#" class="button">Leave Game</button>
					          <input type="hidden" name="game_to_leave_pk" value={{game.pk}} />
					        </form>
							</div>
						</div>
					</div>
					<div class="icon" 
						 style="background-image: url('/static/images/{{ game.sport }}.png');">
						<img src="/static/images/{{ game.style }}.png" alt="skill" class="skill">
					</div>
					<div class="card-text">
						<div class="card-date">{{ game.name }}</div>
						<br>
						<div class="card-location">{{ game.location }}</div>
						<br>
						<div class="card-capacity">{{ game.players.count }} / {{ game.max_number_players }}</div>
					</div>
				</div>
  			{% endfor %}
			</div>
		</div>

future/templates/error.html
<!DOCTYPE HTML>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <title>Pickup</title>
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/home.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/splash.css" />    
  </head>

  <body>

    <div id="navigation">
      <div class="splashTop">
  	   Error
      </div>
    </div>
    
   <div class="facebookLogin">
      <button class="errorbutton">
        <a href="/home/">
          {{errortext}}
        </a>
      </button>
    </div> 
   
  </body>
  
</html>

future/templates/game.html
	 <div id="game" class="search-field"></div>

future/templates/gameDisplayDummy.html
<!DOCTYPE HTML>
<body>

  {% for game in games_list %}
    <div class="game">
      <div> leader: {{game.leader.firstname}} </div>
      <div> game name: {{ game.name }} </div>
      <div> sport: {{game.sport}} </div>
      <div> location: {{ game.location }} </div>
      <div> game_datetime: {{game.game_datetime}} </div>
      <div> style: {{game.style}} </div>
      <div> min_number_players: {{game.min_number_players}} </div>
      <div> max number players: {{game.max_number_players}} </div>

      {% for player in game.players.all %}
        <div> player firstname: {{player.firstname}} </div>
      {% endfor %}
      <br>

      <div>
        <form action="/joinGame/" method="post">
          {% csrf_token %}
          <button>Join Game</button>
          <input type="hidden" name="game_to_join_name" value={{game.name}} />
        </form>
      </div>

      <div>
        <form action="/leaveGame/" method="post">
          {% csrf_token %}
          <button>Leave Game</button>
          <input type="hidden" name="game_to_leave_name" value={{game.name}} />
        </form>
      </div>

      <div>
        <form action="/inactivateGame/" method="post">
          {% csrf_token %}
          <button>Inactivate Game</button>
          <input type="hidden" name="game_to_inactivate_pk" value={{game.pk}} />
        </form>
      </div>

    </div>
  {% endfor %}

  <br>
  {% for game in games_leading %}
    <div> leading game: {{game.name}} </div>

  {% endfor %}

  <br>
  {% for game in games_playing %}
    <div> playing in game: {{game.name}} </div>
  {% endfor %}
</body>

future/templates/gameFormDummy.html
<!DOCTYPE HTML>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <title>Web F. Site</title>
    

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/static/css/home.css" />
    <script src="/static/js/newuser.js"></script>
  </head>

  <body>
    
    {% include 'nav.html' %}
    <div class="break">      
    </div>

    <div id="main">
      <div id="container">
                
        <div class="heading">
          Wombling Creation
        </div>
        
        <div class="content-container" style="width:450px;">
          
          <div class='post'>
            <form action="/createGame/" method="post">
              {% csrf_token %}
              
              <textarea name="name" class="netidform">name</textarea>
              <textarea name="sport" class="firstform">sport</textarea>
              <textarea name="location" class="lastform">location</textarea>
              <textarea name="datetime" class="lastform">datetime</textarea>
              <textarea name="min_players" class="lastform">min_players</textarea>
              <textarea name="max_players" class="lastform">max_players</textarea>
              <textarea name="style" class="lastform">style</textarea>

              
              <div id="bottomForm" style="margin-top:10px;">	
                <select name="year">
                  <option value="2014">Sophomore</option>
                  <option value="2013">Junior</option>
                  <option value="2012">Senior</option>
                </select>
                
                <select name="admin">
                  <option value="ME">Member</option>
                  <option value="FC">Food Chair</option>
                  <option value="OF">Officer</option>
                </select>
                
                <button class="submitButton" style="display:inline;">
                  Create Game 
                </button>
                
              </div>
            </form>
          </div>
          
        </div>
      </div>
      
  </body>
  
</html>

future/templates/nav.html
<div id="navigation">
  <div id="top">
    
    <div class="smallItem">
      <a href = "/lobby/"> Lobby </a>
    </div>
  
    <a href="/lobby/"><img src= {{curUser.pic}} /> </a>
    
    <div class="topName"> {{ curUser.firstname}} {{ curUser.lastname }}</div>
    
  </div>
</div>

future/templates/profile.html
<div id="profile" class="search-field">
	<span class="image-container">
		<img src={{curUser.largepic}}>
        <form action="/logout/" method="post">
          {% csrf_token %}
          <button class="button" style="margin-left: 70px;">Logout</button>
        </form>
	</span>
	<div class="search-query-field">
		<div class="search"></div>
		<form action="/search/" method="post">
	    	<div style="display:none">
	    		<input type="hidden" name="csrfmiddlewaretoken" value="144b205117375ff44efdcd0f54d7003b">
	    	</div>
	    		<textarea class="searchBox" name="query" value="" style="color: black;">Search</textarea>
	    	<button class="button" style="position: absolute; top:20px; right: 5px;">
	    		FILTER
	    	</button>
	  </form>
	  <div class="game-history">
	{% for game in games_in_history %}	
		<div class="past-game">
		<div class="icon" style="background-repeat: no-repeat; 
							height: 150px; width: 150px; clear: none;
							background-size: cover; display: block;
							float: right;
							background-image: url('/static/images/{{ game.sport }}larger.png');"></div>
		<div><em>{{ game.name }}</em> <br> {{ game.get_sport_display }} </div> <br>
		<div class="textual-info" style="height: 155px;">
			Skill level : &nbsp &nbsp &nbsp &nbsp &nbsp {% if game.style == "comp" %}
				Competitive
				{% else %}
			    Casual
				{% endif %} <br>
			Type of Sport: &nbsp &nbsp {{ game.get_sport_display }} <br>
			Location: &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp{{ game.location }}<br>
			Players Playing: &nbsp {{game.players.count}} player(s)<br>
		</div>
        <form action="/joinGame/" method="post">
          {% csrf_token %}
          <button class="button" style="float: right;">Join</button>
          <input type="hidden" name="game_to_join_name" value={{game.name}} />
        </form>
      </div>
	{% endfor %}
	  </div>
	</div>
</div>